# Generated by RenPyTranslator. Uses public Ren'Py screen/action APIs.
init offset = 1100

init python:
    _rpt_panel_language = LANGUAGE_VALUE
    _rpt_panel_corner = CORNER_VALUE
    _rpt_panel_margin = MARGIN_VALUE
    _rpt_panel_font = FONT_VALUE
    _rpt_panel_size = max(18, int(config.screen_height * 0.024))

    def _rpt_show_language_panel():
        # A normal nonmodal screen also works during a splashscreen that
        # suppresses ordinary overlays. Never change the language automatically.
        if renpy.get_screen('_rpt_language_panel') is None:
            renpy.show_screen('_rpt_language_panel')

    if _rpt_show_language_panel not in config.interact_callbacks:
        config.interact_callbacks.append(_rpt_show_language_panel)

screen _rpt_language_panel():
    zorder 210
    modal False
    default expanded = False
    hbox:
        xalign (1.0 if _rpt_panel_corner == 'right' else 0.0)
        yalign 1.0
        xoffset (-_rpt_panel_margin if _rpt_panel_corner == 'right' else _rpt_panel_margin)
        yoffset (-_rpt_panel_margin)
        spacing 4
        if expanded:
            textbutton "한국어":
                id "rpt_language_korean"
                style "_rpt_lang_button"
                text_style "_rpt_lang_button_text"
                selected (_preferences.language == _rpt_panel_language)
                action Language(_rpt_panel_language)
            textbutton "원문":
                id "rpt_language_original"
                style "_rpt_lang_button"
                text_style "_rpt_lang_button_text"
                selected (_preferences.language is None)
                action Language(None)
        textbutton ((">" if expanded else "<") if _rpt_panel_corner == "right" else ("<" if expanded else ">")):
            id "rpt_language_toggle"
            style "_rpt_lang_button"
            text_style "_rpt_lang_button_text"
            action ToggleScreenVariable("expanded")

style _rpt_lang_button is default:
    padding (10, 7)
    margin (0, 0)
    background "#18212de8"
    hover_background "#34485a"
    selected_background "#285b68"

style _rpt_lang_button_text is default:
    font _rpt_panel_font
    size _rpt_panel_size
    color "#ffffff"
    hover_color "#ffffff"
    selected_color "#8fe8ed"
    outlines []
    slow_cps 0
    xalign 0.5
    yalign 0.5
