import json
from pathlib import Path
import shutil
import zipfile
from engine import ROOT, save_json, verify_source
from translation import read_catalog, cache, validate_entry
from replacements import effective_cache, replace_visible, load_rules
from name_hints import ensure_metadata
from display_text import compose, attach_josa

def install_support(project,cfg):
    game=project/'staging/game'; lang=cfg['language']
    from font_policy import install
    from ui_policy import policy
    fontdata=install(project,lang)
    ui=policy(project)
    presentation=project/'data/presentation.json'
    layout=json.loads(presentation.read_text(encoding='utf-8')) if presentation.exists() else {}
    extra=layout.get('literal_replacements',{})
    rules=load_rules(project/'replacements.json')
    extra={k:replace_visible(v,rules)[0] for k,v in extra.items()}
    from translation import display_metadata
    metadata=display_metadata(project,cfg)
    extra={k:attach_josa(v,metadata['names']) for k,v in extra.items()}
    # replace_text sees rendered fragments (including individual lines). Do not
    # feed already translatable UI into it: Save\nDescriptions must stay English.
    extra={k:v for k,v in extra.items() if k not in ui['uses']}
    extra.update({s:t for s,t in ui['menu'].items()
                  if any(not u['translated'] for u in ui['uses'][s]) and t!=s})
    original_cache=effective_cache(project,cfg,apply_ui=False)
    choices={}
    choice_sources=set(ui['choices'])
    for row in read_catalog(project):
        if row['kind']=='string' and row['source'] in choice_sources and row['id'] in original_cache:
            choices[row['source']]=compose(dict(row,kind='dialogue'),original_cache[row['id']],metadata)
    save_json(project/'output/ui-report.json',{'items':[{'source':s,'text':t,
        'policy':'standard Korean' if t!=s else 'custom/original', 'uses':ui['uses'][s]}
        for s,t in ui['menu'].items()], 'bilingual_story_choices':len(choices)})
    # Reuse already translated name strings for pronunciation; no extra model requests.
    import re
    representatives={v['representative'].lower() for v in metadata['names'].values()}
    pronunciations={entry['source'].lower():entry['text'] for entry in effective_cache(project,cfg).values()
                    if entry['source'].lower() in representatives and re.fullmatch(r'[가-힣 ]{1,40}',entry['text'])}
    # This additive file is independent of restored original source files.
    support='''# Generated by RenPyTranslator: Korean + 55% original text.
init 900 python:
    import json as _rpt_json
    _rpt_data = _rpt_json.loads(renpy.file(DATAFILE).read().decode('utf-8'))
    _rpt_language = LANG
    _rpt_fontdata = _rpt_data['fonts']
    _rpt_choices = _rpt_data['choices']
    _rpt_language_before = getattr(gui, "language", "unicode")
    _rpt_literal = _rpt_data['literal']
    _rpt_pronunciations = _rpt_data['pronunciations']
    _rpt_previous_replace = config.replace_text
    def _rpt_replace_text(s):
        if _rpt_previous_replace is not None:
            s = _rpt_previous_replace(s)
        if _preferences.language == _rpt_language:
            return _rpt_literal.get(s, s)
        return s
    config.replace_text = _rpt_replace_text
    config.language = _rpt_language

translate LANG_RAW python:
    _rpt_language_fonts()
    gui.language = "korean-with-spaces"

translate None python:
    _rpt_language_fonts()
    gui.language = _rpt_language_before

translate LANG_RAW style default:
    language "korean-with-spaces"

translate LANG_RAW style gui_text:
    language "korean-with-spaces"

translate LANG_RAW style say_dialogue:
    SIZE_OVERRIDE
    line_spacing 4

translate LANG_RAW style choice_button:
    ysize None
'''
    size=layout.get('dialogue_font_size')
    if size is not None and (not isinstance(size,int) or not 8 <= size <= 100):
        raise ValueError('dialogue_font_size must be an integer between 8 and 100')
    support=support.replace('SIZE_OVERRIDE',f'size {size}' if size is not None else '# Keep original dialogue size')
    datafile='tl/'+lang+'/_rpt_presentation.json'
    save_json(game/datafile,dict(fonts=fontdata,choices=choices,literal=extra,pronunciations=pronunciations))
    support=support.replace('LANG_RAW',lang).replace('LANG',json.dumps(lang)).replace('DATAFILE',json.dumps(datafile))
    # Keep a single support file in the copy-and-paste patch, with Python 2 Unicode literals.
    helper=(Path(__file__).with_name('josa_runtime.py')).read_text(encoding='utf-8')
    support+='\ninit 890 python:\n'+''.join('    '+line+'\n' for line in helper.splitlines())
    helper=Path(__file__).with_name('presentation_runtime.py').read_text(encoding='utf-8')
    support+='\ninit 1000 python:\n'+''.join('    '+line+'\n' for line in helper.splitlines())
    (game/'zz_rpt_korean.rpy').write_text(support,encoding='utf-8')
    from name_translation import install_support as install_names
    install_names(project,cfg,read_catalog(project),original_cache)
    from layout_policy import install as install_layout
    install_layout(project,cfg)
    from display_policy import install as install_reference
    install_reference(project,cfg)
    from language_panel import install as install_language_panel
    install_language_panel(project,cfg)
    from story_hints import restore as restore_hints
    restore_hints(project,cfg)
    report_path=project/'output/replacements-report.json'
    if report_path.exists():
        report=json.loads(report_path.read_text(encoding='utf-8'))
        report['screen_caption_changes']=[{'source':k,'before':v,'after':extra.get(k,k)}
            for k,v in layout.get('literal_replacements',{}).items() if v!=extra.get(k,k)]
        save_json(report_path,report)
    print('Installed Korean font, bilingual layout and name particles in staging',flush=True)

def package(project,cfg):
    rows=read_catalog(project);known=effective_cache(project,cfg)
    for row in rows:
        if cfg.get('_render_ids') is not None and row['id'] not in cfg['_render_ids']:continue
        if row['id'] not in known or (not cfg.get('_repair') and validate_entry(row['source'],known[row['id']],cfg)):
            raise ValueError('Cannot package incomplete or invalid translations')
    check={'checked':False,'reason':'Offline repair uses only the existing project'} if cfg.get('_repair') else verify_source(project,cfg)
    validation=project/'data/validation.json'
    if not validation.exists() or json.loads(validation.read_text())['errors']:
        raise ValueError('Run validate before packaging')
    # Confirm rendered files actually contain the selected cache/override texts.
    from translation import rendered_text
    from translation import display_metadata
    metadata=display_metadata(project,cfg,rows)
    rendered_files={}
    for row in rows:
        if cfg.get('_render_ids') is not None and row['id'] not in cfg['_render_ids']:continue
        if row['file'] not in rendered_files:
            rendered_files[row['file']]=(project/'staging/game/tl'/cfg['language']/row['file']).read_text(encoding='utf-8-sig').splitlines()
        lines=rendered_files[row['file']]
        if rendered_text(lines[row['line']],row) != compose(row,known[row['id']],metadata):
            raise ValueError(f'Rendered file is stale: {row["id"]}; run render and validate')
    reports=project/'output';reports.mkdir(exist_ok=True)
    from output_paths import destination
    output,label=destination(project,cfg);output.mkdir(parents=True,exist_ok=True)
    name=label+'.zip';target=output/name
    instructions=('한국어 자동 번역 초안 패치\n\n'
        '적용: 압축을 풀어 나온 game 폴더를 게임 실행 파일(.exe)이 있는 폴더에 복사해 합칩니다. game/game이 되지 않게 하십시오.\n'
        '실행: 평소 쓰던 게임 .exe를 더블클릭합니다. Python, Ollama, CLI는 플레이에 필요 없습니다.\n'
        '한국어 모드에서 대사·내레이션·선택지는 한국어 위, 원문 아래(55% 크기)로 함께 표시합니다.\n'
        '하단 구석 화살표를 펼치면 한국어 / 원문을 전환할 수 있습니다. 게임에서 영어를 선택했어도 한국어로 돌아올 수 있습니다.\n'
        '기본 메뉴·설정은 고정 한국어 번역, 게임 고유 커스텀 메뉴 항목은 원문으로 표시합니다.\n'
        '이 도구의 이전 패치를 복구할 때도 game 폴더를 같은 위치에 덮어쓰면 됩니다. 번역을 다시 돌릴 필요가 없습니다.\n'
        '제거: game/zz_rpt_korean.rpy, zz_rpt_names.rpy, zz_rpt_layout.rpy, zz_rpt_reference.rpy, zz_rpt_hints.rpy, zz_rpt_language.rpy 및 각각의 .rpyc, game/tl/'+cfg['language']+' 폴더를 제거합니다.\n'
        '기존 다른 한국어 패치가 있는 게임에는 이 패치를 겹쳐 적용하지 마십시오.\n'
        '본문과 UI를 번역한 로컬 모델 초안이며 모든 문장을 사람이 감수한 번역은 아닙니다.\n'
        '이미지에 그려진 타이틀/크레딧과 원어 음성은 포함하지 않습니다.\n'
        '글꼴: 나눔스퀘어 네오, 나눔손글씨 펜, 보조 Noto Sans CJK KR. SIL OFL 1.1 라이선스를 글꼴 폴더에 동봉했습니다.\n')
    (output/'적용방법.txt').write_bytes(instructions.encode('utf-8-sig'))
    stage=project/'staging'; files=[stage/'game'/n for n in ('zz_rpt_korean.rpy','zz_rpt_names.rpy','zz_rpt_layout.rpy','zz_rpt_reference.rpy','zz_rpt_hints.rpy','zz_rpt_language.rpy') if (stage/'game'/n).exists()]
    files += [p for p in (stage/'game/tl'/cfg['language']).rglob('*') if p.is_file() and p.suffix in ('.rpy','.otf','.ttf','.txt','.json')]
    with zipfile.ZipFile(target,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
        for path in files:
            rel=path.relative_to(stage)
            z.write(path,rel.as_posix())
            if cfg.get('_portable_output'):
                dest=output/rel;dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(path,dest)
        z.writestr('적용방법.txt',instructions.encode('utf-8-sig'))
    save_json(reports/'build-report.json',{'model':cfg['model'],'language':cfg['language'],
        'dialogue':sum(r['kind']=='dialogue' for r in rows),'ui':sum(r['kind']=='string' for r in rows),
        'source_verification':check,'package':name,'package_bytes':target.stat().st_size,
        'source_fallbacks':sum(v.get('status')=='source_fallback' for v in known.values()),
        'display':'Korean above original 55%; standard UI Korean; custom menu items original',
        'quality':'Machine translation draft; not a complete human proofread'})
    if cfg.get('_portable_output'):
        # Relative link lets the GUI reopen this result after moving the portable folder.
        import os
        save_json(output/'project-link.json',{'project':os.path.relpath(project,output)})
    print('Output folder: '+str(output),flush=True)
    print(target,flush=True)
